"""Hourly Locational Marginal Price (LMP) for Phoenix.

Approximates APS / SRP-style retail pricing: flat off-peak base, an on-peak
ramp from mid-afternoon into the evening, AR(1) noise, and an additive
spike during grid stress events. Clamped to the challenge's published range.

Depends on ``data/grid_events.parquet`` (generated by
:mod:`src.signals.grid_events`).

Run directly: ``python -m src.signals.lmp``.
"""

from __future__ import annotations

from pathlib import Path

import numpy as np
import pandas as pd

from src.config import CONFIG, seed_for


DATA_DIR = Path(__file__).resolve().parents[2] / "data"


def _diurnal_base(timestamps: pd.DatetimeIndex) -> np.ndarray:
    lp = CONFIG.lmp
    hours = timestamps.hour.to_numpy()
    base = np.full(hours.shape, lp.offpeak_base_usd, dtype=float)
    on = np.isin(hours, lp.onpeak_hours)
    base[on] = lp.onpeak_base_usd
    return base


def generate(seed: int | None = None) -> pd.DataFrame:
    if seed is None:
        seed = seed_for("signals.lmp")
    rng = np.random.default_rng(seed)
    lp = CONFIG.lmp

    events_path = DATA_DIR / "grid_events.parquet"
    if not events_path.exists():
        raise FileNotFoundError(
            "grid_events.parquet missing — run `python -m src.signals.grid_events` first."
        )
    events = pd.read_parquet(events_path)
    events["timestamp"] = pd.to_datetime(events["timestamp"], utc=False)

    timestamps = pd.DatetimeIndex(events["timestamp"])
    base = _diurnal_base(timestamps)

    # AR(1) noise
    n = len(base)
    eps = rng.normal(0.0, lp.ar1_sigma_usd, size=n)
    noise = np.zeros(n)
    for i in range(1, n):
        noise[i] = lp.ar1_rho * noise[i - 1] + eps[i]

    lmp = base + noise

    # Event spike
    is_event = events["is_event"].to_numpy()
    severity = events["severity"].to_numpy()
    spike_band = lp.event_spike_max_usd - lp.event_spike_min_usd
    spike = np.where(is_event, lp.event_spike_min_usd + severity * spike_band, 0.0)
    lmp = lmp + spike

    lmp = np.clip(lmp, lp.clamp_min_usd, lp.clamp_max_usd)

    out = pd.DataFrame({"timestamp": events["timestamp"], "lmp_usd_per_kwh": lmp})
    DATA_DIR.mkdir(parents=True, exist_ok=True)
    out.to_parquet(DATA_DIR / "lmp.parquet", index=False)
    return out


def main() -> None:
    df = generate()
    print(
        f"lmp: {len(df)} hours  "
        f"min=${df['lmp_usd_per_kwh'].min():.3f}  "
        f"mean=${df['lmp_usd_per_kwh'].mean():.3f}  "
        f"max=${df['lmp_usd_per_kwh'].max():.3f}"
    )
    by_hour = df.assign(hour=df["timestamp"].dt.hour).groupby("hour")["lmp_usd_per_kwh"].mean()
    print("mean LMP by hour of day:")
    print(by_hour.round(3).to_string())


if __name__ == "__main__":
    main()
